### PR TITLE
Added the EVE SDE Database Builder

### PR DESCRIPTION
**Pull request by Zifrian**
Added my recent app to the conversion list for use.

### CODE REVIEW

**Comment by polarina** [comment]
Nice. Some of those instructions should be moved to the exporter's README page instead of in this 3rd party documentation. Concentrate on keeping the summary short and highlight the most significant features. Minor details are not necessary.

**Comment by Zifrian** [comment]
Thanks for the feedback. I've cut it down significantly and kept in line with the other two converters.

**Comment by Zifrian** [comment]
Any issues with this edit?

**Comment by Zifrian** [comment]
Anyone going to accept or can I get feedback? I'd like people to know about this tool that I created for the dev community.

**Comment by CarbonAlabel** [comment]
@Zifrian with all the work on the new ESI API, I'm guessing the third-party documentation project has been somewhat abandoned by the devs, at least for the time being.

If you manage to get a hold of one of the devs over on Tweetfleet Slack and ask nicely, they should be able to merge it.

**Pull request merged**
