### PR TITLE
Schema/CallGroups work

### PR DESCRIPTION
**Pull request by timpanogos**
I just finished a dynamic version/endpoint-uri implementation.  I started to enter all of the proper version strings and group names to all of the existing endpoint .md's but wanted to propose a big change before I go add in this information. 

There are endpoints already documented here that are not reported by the options request and root call groups.  There are also endpoints reported there that are not currently in the documentation.  The call groups are a bit of a mess which I see is reflected in the endpoints that are actually in a common group and those that should be.  Part of the goal here is to get a complete list of endpoints even if they are only place holders.  I'm attempting a full/all crest endpoint implementation, and so will be able to help finish these up as I do the json marshalling on each class.

I have written a couple of bugs against the schema/callgroups which would require a schema version change.  If that were to happen, hopefully ccp would avoid the single endpoints to a given group.  Note this first folder name based on group with a file per endpoint is an attempt for discussion.  The new files are junk and simply copies of other files for structure analysis.  

Take a look at this file, initializeVersions method around line 109.

https://github.com/timpanogos/crestj/blob/master/crest-core/src/main/java/com/ccc/crest/core/cache/crest/schema/SchemaMap.java
I columnized the parameters so that the patterns can more easily be seen.  

The first parameter is used to obtain the "base version" string i.e. "application/vnd.ccp.eve.ConstellationCollection"  This is a constant identifier for the json object.  I obtained all of these from the options request.

The second parameter is the current version as reported by the options request.

The third column is the endpoint route as reported by the root call groups.  Note all of the ones with two components to the route.  These are the ones that drove most of the suggested structure.

Please Discuss .... 

commit comments follow:
The forth column is a kludge to couple the version mapping to the uri mapping.  In a bug report I suggested that the base version string be used .. but a different story.
Proposal to match the documenation structure closely to the schema/callgroups structure.
Added placeholders for the following discovered from the schema.
callGroups
corporations
industrySystems
npcCorporations
options
tokenDecode
tournament
virtualGoodStore

### CODE REVIEW

**Comment by CarbonAlabel** [comment]
First of all, this PR in its current form would break the navigation, as you can't just rename and rearrange the files and leave the indexes as they are.

As far as your suggestions go, I'm against them and don't understand the reasoning behind them.

Currently, the docs have reasonable grouping: the character category has endpoints which are accessed through the character resource and affect or provide info about the relevant character, while the EVE category (and the map category) has endpoints representing various global information. I do think both could be further broken down, but definitely not in this way, as I don't see how the list of all races and bloodlines could possibly be specific to any character.

**Comment by CarbonAlabel** [comment]
And on a more personal note: stop overthinking this.

CREST in its current form, with the exception of several endpoints and some other minor issues, is working fairly well and is a great example of a RESTful API, and people are utilizing HATEOAS principles with it very well.

Instead of asking for fairly major changes, which are unlikely to happen anytime soon even if many people wanted them (changes take time), and if I'm understanding them correctly, would break almost every CREST application out there, just use it like anyone else.

If you have some problems with it, ask someone for help and maybe later submit a bug report for that specific issue instead of wasting time dreaming up an overhaul of CREST from the ground up.

**Comment by timpanogos** [comment]
I'm aware the navigation is broken, I simply wanted to bring up discussion on this before doing much of anything on it.  A reorganization of the documentation does not break anything.
  
The current naming does not fit the underlying schema/naming.  What the hell is the "eve" group anyway?  btw, the remaining ones that are in that folder are only there because they did not fit in the current suggested group folders ... perhaps something like "other" or "misc"

The mixing of multiple endpoints in a single file for some groups verses a single file to endpoint is inconsistent.  CCP fixing the schema is not going to break anyone.  It's missing several endpoints as it is and needs fixed anyway.  There were 3 solid bugs without any enhancements.  Normal rest deprecation of the two interfaces (options request and root call group) is not going to break anyone.  

Why all the hate?  I'm working on something that implements all of the crest endpoints (if I can even identify them)  and I'm willing to help.  I would have thought that might be welcome?  ccp-bartender contacted me privately one day about version deprecation detection.  I privately returned him the 3 bugs which he asked me to submit through the system.  

If I'm just being a pain in the ass to ccp, by all means someone form ccp please let me know.  That is why I asked about it in tech-lab forum in the first place.

Now is it possible to have a real discussion on this issue?

**Comment by timpanogos** [comment]
> As far as your suggestions go, I'm against them and don't understand the reasoning behind them.
Please lets discuss the reasoning.

> Currently, the docs have reasonable grouping: ... 

please explain the reasoning on the "eve" and "map" folders.  They both contain public interfaces.  How does the map group differ from say the inventory group (3 endpoints buried in one)?

Also note that the schema's "base version string" is what appears to be a globally unique identifier and hence is the best thing to be using to talk about the object it identifies.  For example I would change a the very top line of every endpoint to something like: 
#Endpoint application/vnd.ccp.eve.ConstellationCollection
#Version: v1+json
Thus reflecting the actual schema naming.

> as I don't see how the list of all races and bloodlines could possibly be specific to any character.

Think of grouping per functionality characters are of a race and bloodline, thus it makes more sense grouped there than eve.  Once again, I would rename eve to other or misc as it contains a mix of functionality that just does not belong to a existing functional groups.

> CREST in its current form, with the exception of several endpoints and some other minor issues, is working fairly well and is a great example of a RESTful API, and people are utilizing HATEOAS principles with it very well.

Funny I actually wanted to depend on HATEOAS and found it pretty broken.

> If you have some problems with it, ask someone for help and maybe later submit a bug report for that specific issue instead of wasting time dreaming up an overhaul of CREST from the ground up.

I posted fairly extensively about this topic on the tech lab forums.  I did not see you or others address these issues there?

**Comment by jonobrien** [comment]
`tokenDecode` is actually `decode` for character token validation, see past PRs on this little tidbit. :wink:

**Comment by timpanogos** [comment]
@jonobrien thus it belongs in the character folder?

**Comment by jonobrien** [comment]
in a previous discussion we had clarified the uses of the endpoint, https://github.com/ccpgames/eveonline-third-party-documentation/pull/190#issuecomment-232301973

I didn't add the information then, but that detail is in the docs already, but that's another PR for another day.

**Comment by timpanogos** [comment]
@jonobrien thanks for the link.  based on that it indeed belongs in the characters folder.

**Comment by jonobrien** [comment]
it would appear we are grouping endpoints as such the `decode` endpoint would probably go into `eve` as it is accessible from the `root` but a PR would decide that for sure.

**Comment by CarbonAlabel** [comment]
I believe the `decode` endpoint shouldn't have a page of its own at all, and should instead be described in a page on CREST walking: it's very special, acting as the gateway to authed endpoints, and could be easily misunderstood if put out of context.

**Comment by timpanogos** [comment]
@jonobrien ah, I see where eve folder came from now ... the problem is the inconsistent group/endpoint schema where some of the schema has a group parent (first uri segment) and some do not.  This is, btw what breaks oop languages from being able to auto-parse the options endpoint. The group type is inconsistent with two actual representations, one for actual groups, one for endpoint being in the group position.  

And yet inventory, market, industry were done wrong and not actually grouped while dogma, sovereignty and opportunities where done right and actually grouped. This inconsistency is reflected in the documentation where first list globed all of the endpoints into a single .md while the latter list has a .md per endpoint.  Note this latter group breaks the eve/root rule.  Thus based on existing schema its broken either way.

I believe its preferable to go with the single .md per endpoint method and group/folder then as we would have hoped cpp might have in the first place and might consider doing at some future time.  In the linked java class that third column where there is only a single uri segment are the ones that should be assumed to be in a group

**Comment by timpanogos** [comment]
@CarbonAlabel crest walking is about moving forward/backward on large data sets.  Part of why I proposed this radical change is I was going to start on a new section ... how to walk schema/callgroups but would want the actual endpoint descriptions to be organized after the schema/endpoints ... with us fudging in favor of groups where the current schema does not reflect it.

**Comment by jonobrien** [comment]
@CarbonAlabel very true. @timpanogos  yeah I've had some issues here and there for parsing it, but I usually just hardcode things when I have to, but I'd prefer not to obviously.

There are probably enough details about the endpoint to warrant a page, but really depends on how specific you are on each endpoint's features.

**Comment by CarbonAlabel** [comment]
@timpanogos It's used to refer both to pagination and to endpoint discovery (another aspect where these docs could be improved). 

One of my problems with your arguments is the way you are using some terms: schema, call groups, object oriented... Could you clarify exactly what you mean by them? The way you are using them makes them seem like buzzwords.

**Comment by timpanogos** [comment]
@CarbonAlabel Any mention of Object, in this PR is in regard to json, whose top most entry and every following '{}' declares a json Object.  Thus it's json's architecture and design which defines Object.  It just so happens that the definition I would like to use is found here: 
[](https://forums.eveonline.com/default.aspx?g=posts&m=6609842#post6609842)
which json objects happen to follow, including self-referencing. 

Now for the two terms I'm introducing.
**schema** is the json tree returned by the httpClient.getOptions() call into any valid endpoint, including the eve root.  It is an endpoint like any other and requires a .md just like the other endpoints.  schema is once again a json term/concept.  This is the first place seasoned rest programmers will be looking when starting with new/unknown json services.

**callGroups** is the json tree returned by the eve root.  It is an endpoint like any other and requires a .md just like the other endpoints.  It provides the endpoints currently supported by the system.  I penned this term trying to follow the concept of the xmlapi's "ApiCallList"

Please elaborate on your first statement, I don't understand pagination and its relationship to discovery that you mention?

> It's used to refer both to pagination and to endpoint discovery (another aspect where these docs could be improved).

**Comment by timpanogos** [comment]
bottom line:  eve's json schema

> This is the first place seasoned rest programmers will be looking when starting with new/unknown json service.  

i.e. eve in this case

The documentation should follow the json schema very closely.  Since the json schema is schizophrenic we should choose dr jekyll instead of mr hyde   root/group/endpoint verses root/endpoint, fudging and documenting where root/endpoint's are moved to some group.

If this is deemed desirable I'm willing to do this rework and add the options and callgroups endpoint .mds as well as a general section on how to walk ccp's schema/callgroups and try them together for dynamic url's and new version discovery  while this is fresh on my mind ... two weeks this old chemo brain has forgotten all.

I can easily spend my efforts on my own special snowflake verses doing documentation which I hate.  rejecting this is not going to break my heart ... I'm really just trying to be a valued contributor to this community as well.

**Comment by jonobrien** [comment]
You might want to just add to the walking section as a start and everyone could always discuss reworks in the future :+1:

**Comment by timpanogos** [comment]
@jonobrien thanks for the suggestion.  I believe this pr has fulfilled its intended purpose to start a discussion about a revamp of the documentation structure and patterns.  The new PR was developed off a fresh fork of the master and is a much smaller piece to try and chew on  ... this pr code branch is dead.

**Comment by CarbonAlabel** [comment]
It's great that you want to start contributing, not so much that you're using different terminology.

> **schema** is the json tree returned by the httpClient.getOptions() call into any valid endpoint, including the eve root. It is an endpoint like any other and requires a .md just like the other endpoints.

What is a `httpClient.getOptions()` call supposed to be? This documentation should be language agnostic, and any Java (or any other language) specific terms are a big no-no. What you are talking about is a HTTP OPTIONS request. If it is returned by a call to any valid endpoint, how can it be an endpoint like any other, or an endpoint of its own at all? It's a representation, which indeed exists for any valid endpoint, and contains the schema/structure/description of all representations returned by the endpoint, including itself.

> **callGroups** is the json tree returned by the eve root. It is an endpoint like any other and requires a .md just like the other endpoints. It provides the endpoints currently supported by the system. I penned this term trying to follow the concept of the xmlapi's "ApiCallList"

We already have a name for it, the root resource/endpoint. It doesn't provide all the endpoints currently supported by the system, only a select list of them, and also provides some info about the current state of the EVE cluster.

CREST is the long-term replacement for the XML API, and they follow different paradigms, so while the XML API won't be going away anytime soon, is still going to be maintained and will need to be used in conjunction with CREST by most serious apps (for the foreseeable future), consider them separate APIs and try to avoid bringing concepts from one into the other.

> I have referenced a fully implemented working dynamic uri/version checking system, centralized and formatted to highlight the issues.

Which one? Are you talking about your CREST library?

> Please elaborate on your first statement, I don't understand pagination and its relationship to discovery that you mention?

Pagination in CREST collections has an uniform implementation, which like endpoint discovery involves following links returned by previous requests, and such methods are often referred to as walking or crawling. Other than that, they don't have much to do with each other.

**Comment by timpanogos** [comment]
> What is a httpClient.getOptions() call supposed to be? 

The term HTTP OPTIONS - sorry I did not know what this was, I has just trying to distinguish between HTTP GET with the intended pseudo code.

> This documentation should be language agnostic, and any Java (or any other language) specific terms are a big no-no.
 
Well the crest (REST) documentation sections should be very json specific and language agnostic, which all of my suggestions are.

> What you are talking about is a HTTP OPTIONS request. If it is returned by a call to any valid endpoint, how can it be an endpoint like any other, or an endpoint of its own at all? 

see new PR, specifically the new CallGroups and Options endpoints, they link each other.

[CallGroups, Options](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/callGroups.md)

They act like any other endpoint, returning a json object graph which is defined by schema for the schema.  Anyone trying to write a dynamic client will want this information.  In A future PR I will attempt modifying the walking section which will reference the new CallGroups (EndpointCollection) and Options .md's

> We already have a name for it, the root resource/endpoint. It doesn't provide all the endpoints currently supported by the system, only a select list of them, and also provides some info about the current state of the EVE cluster.

I'm well aware of this, please point me to the existing endpoint documentation, perhaps my latest PR is redundant?  I would suggest that resource/endpoint is an invalid name.  Following the pattern of other **_Endpoint Name_**'s (see tournament.md for suggested terms) I need to double check the schema and see if they gave us a name for it (**_Access_**)  I think this one is unique.  If not, a better name might be "EndpointCollection".

**Comment by CarbonAlabel** [comment]
I'm sorry that you're taking parts of my replies as insults. Let me try to concisely restate my primary issues with your suggestions/pull requests, based on the comments here, forum posts, and some Slack conversations.

- **Focus on basing the documentation on schemas and computer-readability:** Tools for generating those live already exist (see [here](https://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/index.html#autogenerated-documentation)), so this documentation should be kept as human-friendly as possible: grouping by themes, teaching by example, tips about using specific endpoints and explaining various concepts behind CREST.
- **Intent on the creation of a complete list of endpoints:** One of the concepts behind CREST is to never generate a URL based on some input, but to only use complete URLs provided by a user (possibly with a preset default, usually the root URL), following the links returned by a request to that URL, and repeating the process until arriving to the desired endpoint. A central list of endpoints goes against that concept.
- **This is documentation for the existing EVE APIs:** Documentation on here should be about APIs and resources which are already available or in testing, not proposals. Furthermore, this repository is not for the APIs, it's for the documentation itself, so it isn't the proper place to make suggestions or post issues about the APIs. Though, to be fair, the 'proper' avenues for such feedback leave much to be desired.

Things I agree on:

- Details returned by OPTIONS request need some improvement.
- The documentation needs improvement in many areas.

**Comment by timpanogos** [comment]
wow, we are nowhere near on the same page.  Thus let's focus in a bit tighter and only consider/talk about the proposed tournament.md file.  

terms:  template == proposed template == tournament.md in the following questions.

> Focus on basing the documentation on schemas and computer-readability: Tools for generating those live already exist (see here), so this documentation should be kept as human-friendly as possible: grouping by themes, teaching by example, tips about using specific endpoints and explaining various concepts behind CREST.

1. Please elaborate on what it is about template and CCP's scheme for this object bothers you.
2. What "computer-readability" issues do you have with the template 
3. I assume the "Tools" you linked was intended to take me to the auto document builds.  What is it about the template that relates to those tools that you dislike?
4. Please elaborate on what you find non-human friendly about the template.
5. What do you find about the template that keeps it from being  a good example, providing tips, and various crest concepts?

> Intent on the creation of a complete list of endpoints: One of the concepts behind CREST is to never generate a URL based on some input, but to only use complete URLs provided by a user (possibly with a preset default, usually the root URL), following the links returned by a request to that URL, and repeating the process until arriving to the desired endpoint. A central list of endpoints goes against that concept.

You are wrong on this and have stated the exact opposite of a well written crest client should do.

> This is documentation for the existing EVE APIs: Documentation on here should be about APIs and resources which are already available or in testing, not proposals. Furthermore, this repository is not for the APIs, it's for the documentation itself, so it isn't the proper place to make suggestions or post issues about the APIs. Though, to be fair, the 'proper' avenues for such feedback leave much to be desired.

1. What exactly is it about the template that is not about existing EVE APIs, resources?
2. What about the template do you find is not about documentation but is about making suggestions, posting issues etc?

**Comment by timpanogos** [comment]
@jonobrien @CarbonAlabel
Release candidate up, I'm moving back to coding.

See this thread for the actual PR [actual release candidate](https://github.com/ccpgames/eveonline-third-party-documentation/pull/215)

**Comment by jonobrien** [comment]
@timpanogos can you close this since ["this pr code branch is dead"](https://github.com/ccpgames/eveonline-third-party-documentation/pull/212#issuecomment-244286520) ?

**Comment by timpanogos** [comment]
@jonobrien there is a lot of conversation in here I don't want to lose quite yet.  If I close it is it gone?

**Comment by jonobrien** [comment]
no you can reopen it whenever

**Comment by jonobrien** [comment]
well it's a PR, so not sure

**Comment by CarbonAlabel** [comment]
A closed pull request will still be available under closed pull requests (both the commits and the conversation) and you can reference it anytime, so feel free to close this.

**Comment by jonobrien** [comment]
oh right, I forgot there was a section for closed. :laughing:

**Pull request closed without merging**
