### PR TITLE
Char - Mailing Lists

### PR DESCRIPTION
**Pull request by clonerworks**
Char - Mailing Lists

### CODE REVIEW

**Comment by polarina** [comment]
Where's the commit for mailing lists?

**Comment by Regner** [comment]
O_O

**Comment by clonerworks** [comment]
Lets just say epic fail on my part here lads.

**Comment by Regner** [comment]
When possible can you add a description to the endpoints file for this as well.

**Comment by clonerworks** [comment]
No problems I will start doing that, do you mind if I bulk add some in my next pull request for previous pull requests I have done where I didn't do this?

**Comment by polarina** [comment]
That's all right as it's just a bulk of new descriptions concentrated on a single page. :-)

**Pull request merged**
