### PR TITLE
Add in-game browser docs from EVElopedia

### PR DESCRIPTION
**Pull request by nezroy**
A straight import of the in-game browser documentation from EVElopedia. Very minor formatting and content changes.

### CODE REVIEW

**Comment by JimiC** [comment]
In each code block specify the language for proper highlighting.

**Comment by CarbonAlabel** [comment]
With the IGB on its way out, and CREST coming very close to matching its functionality, is there a point in adding this to the docs?

**Comment by Regner** [comment]
Gotta agree with Carbon. We plan on deleting the IGB in about 4 to 5 months (proper announcement coming in June).

**Comment by Regner** [comment]
Yea, going to close this for now. Really do appreciate the effort, it means a lot that you would take the time to do this. However the IGB is going away this year and I don't want to encourage development with it.

**Pull request closed without merging**
