### PR TITLE
crest /tournaments/ docs

### PR DESCRIPTION
**Pull request by jonobrien**
I tried to follow the current method of outlining endpoints and documenting responses, etc.

### CODE REVIEW

**Comment by jonobrien** [comment]
It would definitely be useful to have some format for grouping our docs so we could reference sections or individual endpoints instead of a single file for all of the associated endpoints.

**Comment by timpanogos** [comment]
@jonobrien 

> It would definitely be useful to have some format for grouping our docs so we could reference sections or individual endpoints instead of a single file for all of the associated endpoints.

I really liked @CarbonAlabel navigation section. for breaking up the endpoints at the same time showing how to walk it.

Try this flavor: https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/misc/tournament/tournamentCollection.md.  Note indexed building of full url's is also valid and should be noted.

**Comment by timpanogos** [comment]
FWIW, you have my vote for this PR to happen anytime.

**Comment by jonobrien** [comment]
I'll add navigation later, I was just posting this as a wip as I've been working with these endpoints for a few months now, noted a few nuanced points for each endpoint as I found them.

**Comment by jonobrien** [comment]
some notes on some other findings, as they still exist as bugs #199 with CCP support ticket still status:open, and hopefully everything is fixed for AT XIV :wink: CCPSoon(tm) :wink:

**Comment by CarbonAlabel** [comment]
@jonobrien Have you tried if the endpoints are working on SISI? According to this [dev blog](https://developers.eveonline.com/blog/article/yc118.8-crest-features), there should be a fixed version there, but I haven't noticed them acting any differently than the ones on TQ.

**Comment by jonobrien** [comment]
no, I've been working off tq as the docs are in tq for the most part I think, and I have been meaning of looking at the sisi endpoints.

**Comment by jonobrien** [comment]
also @CarbonAlabel that devblog only mentions endpoints I haven't wanted to mess with yet.  I have avoided the `/realtime/` and `/static/` endpoints, but have noticed their existence before as well.

**Comment by jonobrien** [comment]
#199 still happens on sisi with errors for root tournament ids saying errors, where I can hardcode other endpoints for the first 7 or so series and their data exists, as poorly explained in that issue.

**Comment by timpanogos** [comment]
ccp-bartender noted to me just the other day that https://api-sisi.testeveonline.com/tournaments/1/ should be fixed on sisi upon next restart and that /9/ worked for at the time being.  I just double checked and id's 1 to 14 indeed return valid information now., thus #199 seems resolved for next release

**Comment by jonobrien** [comment]
@timpanogos yes I noted in my issue that only the first 7 were not returning results, the last 7 were fine.

**Comment by jonobrien** [comment]
@timpanogos if you haven't already, the json in this PR is from the endpoints accessible from the root tournament endpoint.

I just checked sisi and they(1-7) do not return valid data for `tournament/id/`

**Comment by timpanogos** [comment]
@jonobrien I looked at all 14 and got responses.  Just from right now I got a huge response for `/1/`

note this just changed:

13:48:23.895 WARN  [CccBlockingExecutor-4] c.c.c.c.c.c.t.TournamentGetSeries$Structure - outgoingLoser has a field not currently being handled: 
outgoingLoser={"href":"https://crest-tq.eveonline.com/tournaments/1/series/124/"}

i.e. they added outgoingLoser along with the existing outgoingWinner

partial:
13:48:23.900 DEBUG [CccBlockingExecutor-4] c.c.c.c.c.c.t.TournamentGetSeries - Series
	pageCount: 1
	pageCountStr: 1
	totalCount: 126
	totalCountStr: 126
	teams: 
		TeamInfo
			length: 1
			lengthStr: 1
			redTeam: 
				TeamWrapper
					team: 
						Team
							teamName: Circle-Of-Two
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/1/
...

**Comment by timpanogos** [comment]
> if you haven't already looked at it, the json in this PR is from the endpoints accessible from the root tournament endpoint.

oh yea, and loved having them ty ... yes PR should happen anytime before my stuff, which I assume will basically merge into what we all agree upon based off of @CarbonAlabel pattern.

damn work keeps pulling me away from finishing the "tournamentGroup.md" I promised soon as a change proposal to carbon's current navigation ... it's soonerish now

**Comment by jonobrien** [comment]
@timpanogos yeah I saw the existing outgoingWinner before, are you sure you are checking sisi? those href's are for tq

**Comment by timpanogos** [comment]
@jonobrien thanks for the heads up on the sisi, I'm at work and did not update my properties file to point to it... at least my detection for new/unknown fields is working.
1..14 still worked for me .. snippet follows:

	pageCount: 1
	pageCountStr: 1
	totalCount: 126
	totalCountStr: 126
	teams: 
		TeamInfo
			length: 1
			lengthStr: 1
			redTeam: 
				TeamWrapper
					team: 
						Team
							teamName: Circle-Of-Two
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/1/
			blueTeam: 
				TeamWrapper
					team: 
						Team
							teamName: SCUM.
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/64/
			matchesWon: 
				MatchesWon
					redTeam: 1
					redTeamStr: 1
					blueTeam: 0
					blueTeamStr: 0
			matches: 
				ExternalRef
					url: https://crest-tq.eveonline.com/tournaments/1/series/0/matches/
					linkType: null
			self: 
				ExternalRef
					url: https://crest-tq.eveonline.com/tournaments/1/series/0/
					linkType: null
			winner: 
				TeamWrapper
					team: 
						Team
							teamName: Circle-Of-Two
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/1/
			loser: 
				TeamWrapper
					team: 
						Team
							teamName: SCUM.
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/64/
		TeamInfo
			length: 1
			lengthStr: 1
			redTeam: 
				TeamWrapper
					team: 
						Team
							teamName: Of Sound Mind
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/32/
			blueTeam: 
				TeamWrapper
					team: 
						Team
							teamName: YOUR VOTES DON'T COUNT
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/33/
			matchesWon: 
				MatchesWon
					redTeam: 0
					redTeamStr: 0
					blueTeam: 1
					blueTeamStr: 1
			matches: 
				ExternalRef
					url: https://crest-tq.eveonline.com/tournaments/1/series/1/matches/
					linkType: null
			self: 
				ExternalRef
					url: https://crest-tq.eveonline.com/tournaments/1/series/1/
					linkType: null
			winner: 
				TeamWrapper
					team: 
						Team
							teamName: YOUR VOTES DON'T COUNT
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/33/
			loser: 
				TeamWrapper
					team: 
						Team
							teamName: Of Sound Mind
							teamUrl: https://crest-tq.eveonline.com/tournaments/teams/32/
		TeamInfo

**Comment by jonobrien** [comment]
tournament1

I don't see it working on the root. I'm not questioning other endpoints off the root working, as I documented them as working on tq in this PR

**Comment by jonobrien** [comment]
tournament1verified


-  still, not the point of this PR, DOCS are ok to merge for current api results, unless others find issues.

**Comment by timpanogos** [comment]
still, not the point of this PR, DOCS are ok to merge for current api results, unless others find issues.

**Comment by jonobrien** [comment]
fixed all index alphabetical orderings on index pages in my PRs

**Comment by polarina** [comment]
Thanks! Cherry-picked as 4ae75df35d4a65897886f93691203196b050f1bc.

**Pull request closed without merging**
