### PR TITLE
Added eve-reftypes

### PR DESCRIPTION
**Pull request by clonerworks**
Added eve-reftypes

### CODE REVIEW

**Comment by Regner** [comment]
I assume you see the conflicts that need to be fixed?

**Comment by clonerworks** [comment]
I did and make the mistake of hitting push not cancel. Is there a way you can role it back?

**Comment by polarina** [comment]
Is there a reason you can not make alterations to the files as a new commit? The one you sent us looks fine as far as I can tell.

**Comment by clonerworks** [comment]
Thanks for having a look @polarina.
I will follow your advice and do a new commit if required.

Love your work CCP guys!

**Pull request merged**
