### PR TITLE
A collection of minor fixes and additions.

### PR DESCRIPTION
**Pull request by Regner**
* Removed "new" from "this is a new" in the main index since this isn't really "new" anymore
* Ported the kill mail hash formula from the now deleted evelopedia wiki
* Added a new industry page to the formulas section
* Added a table for research multipliers to the industry formulas
* Added a sample of how to calculate the PI production chart
* Cleaned up the guidelines page so the guidelines are a little easier to read and added a little more details
* Cleaned up the FAQ section in the license section so it is a little easier to read
* Added Succeeded and Failed values to the industry const of the XML API

### CODE REVIEW

**Comment by polarina** [comment]
Oh, my. What happened to one commit per logical change? :)

**Comment by Regner** [comment]
I got enthusiastic and carried away. >.< Plus didn't feel like doing 1 PR for each of those small changes. :(

**Comment by polarina** [comment]
I don't mind one pull request as long as it has many cleanly separated commits. :)

**Comment by Regner** [comment]
Oh... guess I am a bit different there. I like PRs to be one nice re-based commit that explains it real nice.  :(

Happy to go back and make them individual commits.

**Comment by polarina** [comment]
Ideally, sure. Pull requests are just there for code review purposes. Commits are the real bread though, because that's what people will go through when deciphering history.

**Comment by deadlybulb** [comment]
You know you guys sit like two desks away from each other, right?

**Comment by Regner** [comment]
We do when we are at the office... I however was not at the office at the time.

**Comment by JimiC** [comment]
lol This PR relates to me in more than one ways, cause I too do like the @Regner 1 commit approach and @polarina has clearly a point here (and should be the preferable way) in such cases.

So to clear things up (and in my mind)
The way you submit the PR should be "feature/bug fix" driven.

- If you make one bug fix, use one commit and do one PR.
- If you make multiple bug fixes separate them via different commits and do one PR.
- If you make a feature use one commit and do one PR.
- If you make multiple features separate them in more than one PR (use of branches are ideal) and of course use one commit, one PR, per feature.

Hope this guideline helps people (and acted as a reminder to me also).

**Comment by Regner** [comment]
Thanks for writing that down @JimiC, looks really good.

**Pull request closed without merging**
