### PR TITLE
Merge multi-level index files

### PR DESCRIPTION
**Pull request by CarbonAlabel**
Starting from the home page of the docs, if I want to get to the documentation page of a specific endpoint, I need to first load the index page of the desired top-level category, then the index page of a subcategory, and finally the endpoint page itself.

By using only one index page per category, a user can go straight from the top-level category index to the endpoint page, eliminating a page load from the process, which may serve as a big improvement to UX, especially on slower connections.

### CODE REVIEW

**Comment by JimiC** [comment]
You do realize that your changes are affecting the left menu navigation, not to mention that your way creates a bloated index page.

**Comment by CarbonAlabel** [comment]
Yes, I'm aware. It affects the nav menu in the same way it affects the index files: you can go a level deeper without an additional page load. (That was my primary motive.)

It does make the index files more bloated, but I see the faster navigation menu as a preferable trade-off.

**Comment by JimiC** [comment]
Not having a bloated navigation page was the idea when we moved from `mkdocs` to `Sphinx` with markdown support.

Having to scroll the navigation page, to find the page you were looking for, was not a great user experience.

**Comment by CarbonAlabel** [comment]
Not sure how others do it, but I exclusively use the navigation bar and don't even look at the index pages themselves, so it is a great UX improvement for my use case.

What I would have preferred was to have the entire documentation tree included in the navigation bar without modifying the index files, but my tries at playing with the config files were unsuccessful. I'm assuming what I wanted would require some modification to the build tools.

**Pull request merged**
