### PR TITLE
Easier navigation via ToC - variation 1

### PR DESCRIPTION
**Pull request by HelOWeen**
Replaces pull request #28 

Complete ToC at the top of the document. This might be to long. See therefore variation 2, where several ToCs are place at the top of each section (account, api, char etc.)

### CODE REVIEW

**Comment by Regner** [comment]
I like it all being together at the top like that, at the same time however it is really long and will just get longer.

Should we maybe consider different pages?

**Comment by HelOWeen** [comment]
> Should we maybe consider different pages?

Ha! That was my first thought when I had a look at the repository. But I thought "_There must be a reason for crunching eventhing into one file._" I'm all for splitting things up, even down to one page per endpoint ...

**Comment by HelOWeen** [comment]
OK, serious suggestion:

We keep endpoint.md as an entry point to the various separate endpoint pages. We keep the ToC there. With no content but the ToC, the ToC can "spread a bit" and provide a one line sentence about what the endpoint is about in addition to linking to the separate page for that endpoint. So that newcomers to the APi get a clue where to look for what.

If we go for this scenario, the decision to make is wether each endpoint becomes a separate file _(like xmlapi_account_accountbalance.md)_ or if we long for fewer files and split them amongst the main categories like /account, /api, /char etc.

I'd personally go for one endpoint per page/file. Results in a bunch of files, but should make merging pull requests less painfull than with one big file.

**Comment by HelOWeen** [comment]
See #31 for an example of my above suggestion.

**Comment by Regner** [comment]
This is superseded by #31

**Pull request closed without merging**
