### PR TITLE
dynamic discovery of crest authed character endpoints

### PR DESCRIPTION
**Pull request by jonobrien**
further increase endpoint discovery via the `decode` endpoint from CREST roots.

### CODE REVIEW

**Comment by bahrmichael** [comment]
Can't access the decode endpoint.

```json
{
  "message": "Unexpected exception thrown of type <class 'eve.server.script.eveserver.crestapi.errors.accessDeniedForbiddenError.AccessDeniedForbiddenError'>",
  "key": "unexpectedException",
  "exceptionType": "InternalServerError",
  "refID": "662febdc-efd6-4f06-9ab0-2e441f0c9c59"
}
```

**Comment by CarbonAlabel** [comment]
@bahrmichael are you sure you are making an authed request?

**Comment by bahrmichael** [comment]
Nope. Just a plain GET request. Overlooked that.

**Comment by Regner** [comment]
Decode isn't about getting a list of authed endpoints, it actually links to a public resource, it is about linking to the character the token belongs to.

**Comment by jonobrien** [comment]
Is there a devblog I missed about that detail?

**Comment by CarbonAlabel** [comment]
@jonobrien afaik it's been that way since CREST's inception.

**Comment by jonobrien** [comment]
thanks for clarifying. :+1:

**Comment by jonobrien** [comment]
so the crest api is character specific information.  Therefore the data returned via an authed call to `<root>/decode/` is all character information allowed via your defined scopes, or am I missing something again?

Yes I can hit the character endpoint publicly, but the authed endpoints do not work without a token anyway. Therefore calling `/decode/` with the token returns my accessible endpoints anyway. How is this any different than acquiring all authed scopes dynamically?

What scopes are not returned under an authed call to the `/decode/` endpoint? Market data is public, obviously.  I can't find any, except corporation scopes (which are not working on crest? but are ok via xml)

**Comment by Regner** [comment]
The purpose of `decode` is list who owns the token. For example if this was a user token it would link to the user. A token could also allow access to more resources than are found from the `/character/<character_id>/` resource, such as corporation resources.

The `decode` resource has nothing to do with finding out what scopes a token has. For example the token could have no scopes and not allow any access to private information, but the scope is still for a given character and so the `decode` resource would still link to the correct `character` resource.

**Comment by Regner** [comment]
The decode resource has nothing to do with scopes really.

**Comment by jonobrien** [comment]
Ah ok, thank you. That is very useful information.

**Comment by Regner** [comment]
Glad I could help :)

**Pull request merged**
