### PR TITLE
added /corp/CorporationSheet.xml.aspx xml api endpoint documentation

### PR DESCRIPTION
**Pull request by Marcon**

### CODE REVIEW

**Comment by Regner** [comment]
Merged, feel free to add yourself to the CONTRIBUTORS file :)

**Comment by deadlybulb** [comment]
Isn't the cache timer something like 2 hours now for CorpSheet?  The example response actually shows 6 hours, but I think that was reduced at some point.  Also, you should update endpoints.md with a one line description of CorporationSheet.

**Comment by polarina** [comment]
The cache timer for `corp/CorporationSheet` is currently set to 357 minutes.

**Comment by Marcon** [comment]
@polarina is correct. Current cache timer for CorpSheet is 5 hours 57 minutes.
I will create new PR with fixes. Also I include in PR update for endpoints.md

**Pull request merged**
