### PR TITLE
SDE format proposal

### PR DESCRIPTION
**Pull request by deadlybulb**
Here's a first crack at creating documentation for SDE tables.  Much of these can probably be auto-generated once we agree on a format.  I've done the following:

* lead off with the table name and a short description
* record the SQL schema in 2008 format (more or less standard).  This is to standardize the type names across all the various DB formats out there.
* record the columns with xrefs to other tables and a short description
* I included an xref if the inner join on the given column between the two tables was non-empty.  The SDE export doesn't record most of these foreign keys (presumably because they are either not used this way or are not really foreign keys), so I went with a simply join check instead.

### CODE REVIEW

**Comment by Regner** [comment]
Couple of questions:
* Do we want to base this off of the format Steve outputs our what the SDE actually ships? Steve giving all MySQL and the SDE being a mix of SQLite3, MSSQL, and YAML.
* The schema feels a bit redundant to me. The MSSQL scripts include the create scripts don't they? If the columns table included the primary key and NOT NULL information then the schema wouldn't be needed at all.

**Comment by deadlybulb** [comment]
Hmmm, the first question is a tough one.  My gut is that we want to document the raw SDE format for a couple of reasons:

1. Steve may stop doing conversions one day (shudder).  It's likely someone else would pick up the job, but unless CCP plans to take this over we probably want pristine raw docs.
2. Steve doesn't convert everything, e.g. graphicIDs.yaml
3. Some conversions are subject to interpretation, e.g. typeIDs.yaml

That said, I don't know of anybody who uses the raw dumps instead of Steve's conversions.  We could put a note saying as much in the "Intro" sectiion of the SDE are in the docs.  It'd also be nice if Steve kept a log of how he interprets various conversions from yaml to SQL.  He does this in his forum posts, but I don't think he records this on his site.

RE: schema, agree it's redundant.  I added it there to capture attributes like default value and PK.  I like your suggestion to just add those to the table.  I'll make those changes and push shortly.

**Comment by Regner** [comment]
Agreed on all points.

**Comment by fuzzysteve** [comment]
https://github.com/fuzzysteve/yamlloader ;)

**Comment by deadlybulb** [comment]
Ok, nuked the SQL schema section and added attribute columns instead.  The format is similar to what you'd see in a DB IDE (e.g. MySQL Workbench).  Only thing I'm not crazy about is rows tend to run long to the right.  Not sure there's a great fix for that.

**Comment by HelOWeen** [comment]
If this isn't the result of an automated output _(which might do it that way)_, I'd replace the HTML checkbox indicating True/False for NULL etc. with a simple "True"/"False" in the table.

**Comment by deadlybulb** [comment]
This isn't automated output.  Once we settle on a format I'll write code to do that off the raw dump.  I've pushed a version which is slightly more compact.  Ideally I'd right justify the attributes but that would require some style stuff.  Not sure if we want to get that fancy.

**Comment by fuzzysteve** [comment]
I'm working up a new set of loaders for the yaml data (as there's a strong suggestion that all the data will be moved in there.) For now, I'm maintaining control of the repo. But I'll take suggestions at the very least ;)
https://github.com/fuzzysteve/SDE-loaders

**Comment by deadlybulb** [comment]
Question: do we want to go with the "file per table" format to match what's being done for the XML API endpoints?  Seems like we should to be consistent.

**Comment by HelOWeen** [comment]
I think that's a good idea.

**Comment by Regner** [comment]
Sorry for being so slow. Agreed on the table per page idea. It adds a lot of files but makes history, diffing, merging, and such easier and potentially even viewing and linking.

**Comment by JimiC** [comment]
Let me also drop in into your conversation. Unfortunately I have to object as Steve's conversions are not the only ones that support the MSSQL recreation from the SQLite3, MSSQL dump and Yaml files. In case you guys don't know already, I have created and since maintaining a tool called "SDEExternalsToSql", that it's also used internally in EVEMon. The problem here is, that the path of the schema I chose to follow is non-compatible with that of Steve's. From my side I tried to follow the basic concepts of CCP in creating the new tables and kept the schema of the dropped tables that CCP used, for backwards compatibility.

Adding to the above, now that Microsoft is releasing DNX Core, I have the intention to port the tool to it and make it cross-platform. Not to add that this way it will be possible to add support for other DB's.

So, in that case there will be 2 SDE loaders (mine and Steve's) that will produce totally different schema.

Conclusion: If you move forward with this proposal you are practically canceling my tool and project.

**Comment by fuzzysteve** [comment]
My suggestion is:

Document the base form.

Then there can be /additional/ documentation added for the other forms. So people who maintain an alternate version can keep it documented here.

**Comment by JimiC** [comment]
Unfortunately, Steve, your suggestion leaves the door open for others to create their own schema, potentially altering the base schema as tables continue to drop from the MSSQL dump and move to other formats. My suggestion is to reach a mutual agreement, you and I, with CCP's input on the base schema. How does that sound?

**Comment by deadlybulb** [comment]
Hi Jimi.  Thanks for joining the conversation.

The proposal on the table is to document the SDE in the form released by CCP.  This particular pull request is proposing a format for things that happen to be MSSQL tables at the moment.  But there will be other PRs for the other formats eventually.  If the trend of migrating out of SQL continues, then this documentation will reflect that migration as well.  As was discussed much earlier, a main goal is to have pristine docs of the raw format.  This gives everyone a common and CCP controlled basis from which to work.

My original ask of Steve, and I would ask this of anyone providing their own version of the SDE, is to keep a clean log of how they are interpreting and transforming the SDE into another form.  We COULD link to the various interpretations in the "Intro" section of this doc.  But I'm not entirely in favor of that as it will become necessary to curate the list over time, and I'm not sure CCP wants to have that responsibility.  We could debate that further, but I'd suggest a different PR then.

**Comment by JimiC** [comment]
@deadlybulb
Correct me if I'm wrong then on what is proposed here.
1. Docs should __always__ reflect the tables that are in the MSSQL dump of the __latest__ SDE that CCP publishes.
2. Reference to each tool that loads the SDE back into a DB.
3. Each tool maintainer should have the responsibility to publish the schema of the recreated DB, including schema differences between DB's (conversions).

**Comment by deadlybulb** [comment]
That all looks good to me with the addition that I think we should doc the non-tables in CCP's version of the SDE as well, e.g. YAML, any SQLite that CCP releases, etc.

**Comment by HelOWeen** [comment]
@JimiC 
looking ahead, with CCP's intention to move more/all stuff out of MSSQL, we need to maintain two DB schema documentations. One, as you suggested, that always reflects the current SDE official SDE. So I'm fine with what you suggested above.

And a second one of a future _SDE-with-all-YAML-SQLite-whoknowswhatelse-stuff-reimported_. The later basically being the schema we 3rd party devs like to work with. And from which the various conversion tools would than spin off their releases. IIRC, CCP Tellus _( @Regner, poke Tellus to join this repository)_ suggested a community maintained tool, which recreates the full blown SDE _(what Desmont's SDEExternalsToSql currently does)_. This would leave us with
1. __One__ officially documented SDE.
2. __One__ community-developed and offically signed off tool to create the above SDE from whatever sources CCP may use in the future.
3. The possibility for whoever wants to spin his own conversion from that MSSQL SDE to _(other format)_ to do this upon a documented and officially signed off SDE, which can be reliably created but the mentioned "reimport tool".

**Comment by JimiC** [comment]
@deadlybulb Agreed. non-MSSQL dump files should also be documented.
@HelOWeen The problem to what you are saying in 2. is exactly what is my concern. Currently we don't have a community-developed tool but 2 tools that are maintained by individuals. And my problem is not which tool will prevail but to come to an agreement of a common schema of the reimported DB.

**Comment by Zifrian** [comment]
Just a few thoughts on the conversation here. I agree with Jimi's concerns, CCP and future third party devs relying on potentially multiple conversions and tools of other third party devs is an issue. It gets even more tricky when we expect those people to maintain documentation of changes. Many of us do this as a hobby and we come and go quite frequently. In the end it's not our job and it's not a stable system to provide a format that we and future devs can rely on. Only CCP can provide that.

As far as people that use the raw data, I do but only for my own purposes. I wrote a simple little importer to build the tables how I want to use them. But as CCP moves to YAML for everything, its getting more frustrating to update my importer because I don't know what the data really looks like without working with the new YAML files. If I rely on a conversion, then I'm up to the changes he or she makes to the schema.

I guess my question is what is the "correct" schema of the non-MSSQL/SQLite tables and who would provide that information? Unless I'm missing it, I don't know what the table schema is for the typeIDs.yaml or blueprints.yaml and that leaves it open to my interpretation. Is this something CCP could provide somehow? I think if the base schema for all files is provided, and we were able to document it, then it would provide a standard for conversions for everyone.

**Comment by aineko-m** [comment]
I think the semantic description of the data (with all their non-obvious meanings and special cases) is more interesting than the technical schema description. The semantics of certain data is also likely the same regardless if it's present as a database column or a field in a YAML file, so I'm not per se partial to one schema or another. However, for the sake of being able to provide example SQL queries, having a complete SQL schema as reference is required, so a unified Steve/JimiC schema would be good.

As for the pull request, it looks like the table names in the xrefs are not camel-cased correctly.

**Comment by JimiC** [comment]
Just FYI here is the DB schema I create with the SDEExternalsToSql tool.
https://gist.github.com/JimiC/648318fd105ca73a5423

**Comment by Regner** [comment]
OK, so picking this conversation back up at last. Before I start throwing out new things to consider does anyone have any new opinions on the topic?

**Comment by deadlybulb** [comment]
My summary of where we ended up so far is something like:

* We want at least one set of pristine docs based exactly on what the SDE looks like when CCP ships it.  For this particular CR (if we don't abandon outright):
  * I need to go back and make sure the docs match the MSSQL tables
  * We wanted to move to a table per file format
  * We probably want to clearly delineate the various sections of the SDE (e.g. MSSQL vs SQLite vs YAML)
* There was an ask to at least list, if not include the documentation for, various third party conversions.  My **opinion** is that a **list** is reasonable if CCP wants to curate.
* There was an ask to consider adopting some sort of official third party conversion and/or associated docs.  My **opinion** is that if we're going to do that, then CCP might as well adopt the converted format and produce the SDE in that form.  Third party devs come and go (someone else made this point), so another set of docs will go stale quickly.

**Comment by HelOWeen** [comment]
@deadlybulb 
My opinion:
* A list of 3rd party conversions should be added. New EVE 3rd party come all the time, even if they have been players for quite a while. The demand for data in a format they prefer to work with is always high upon their asking list.
* Not sure what to think about your second point, though. Yes - 3rd party devs come and go. But given that this tool's supposed to be open source and "CCP featured" _(in lack of a better term)_, pointing to it (and the documentation) here in the official docs might help to drive the attention of new devs towards that tool/docs, if the main maintainers were to leave.

**Comment by deadlybulb** [comment]
If CCP is willing to bless a particular conversion tool I think that's fine.  This has certainly worked for other tools, even closed source like EVEMon, where the set of maintainers has changed over time.

**Comment by blitzmann** [comment]
FYI EVEMon is open source. >_>

**Comment by JimiC** [comment]
We don't want CCP to favor or adapt any conversion tool, at least that's not the goal here. We only want CCP to set the standard of the DB schema so that any tool that deals with the SDE has a base reference.

**Comment by Regner** [comment]
Agreed, unless there is an official CCP conversion the documentation should reference what CCP offers. I am totally down with having a section that links to or talks about the different conversions that are out there though.

**Comment by HelOWeen** [comment]
I wasn't really after _CCP_ favoring/endorsing a certain _tool_, but rather after _drawing the attention_ of interested _3rd party devs_ towards that tool and potentially releave you, Desmont and Steve, from a bit of the burden. And the most prominent place to link such a thing is obviously this doc. But I'm fine with whatever will be decided.

**Comment by Regner** [comment]
I think linking to them and mentioning them is fine. But the documentation on what the SDE is and what the columns are for example should be based on the actual SDE.

**Comment by Zifrian** [comment]
I agree with what Hel and Jimi have said, so I won't repeat their points. I'd just add though that I think if you go on linking conversions, you are going to add another thing to update and maintain, which takes away time from making the current resources the best they can be. I don't think it's the job of anyone at CCP to maintain a list of third party conversion tools for users. 

I'd focus on core resource support - SDE schema, CREST, APIs, documentation(!) and then only supporting new features to the core resources. Anything that happens after the 3rd party devs do with those resources wouldn't be in CCPs lane (outside of feedback on the services). 3rd party devs are going to come and go but those won't have any affect on CCP providing consistent, core resources for them. Leave the sharing of other tools to the devs who made them.

**Comment by deadlybulb** [comment]
Made the following updates:
- wrote a short intro section covering the three types of data in the SDE
- created MSSQL, SQLite and YAML sections to index documentation for those data types
- created separate files for invItems and invNames documentation
- removed tableref.md which is now subsumed by mssql.md, sqlite.md and yaml.md

**Pull request merged**
