### PR TITLE
Some Additions

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Add bloodlines, races and characters table
Update some data
Rename type and types to inventory and add group/groups and category/categories
Fix some typos
Add api versions to inventory endpoints.

Note:  Its including some commits from a different branch that were already merged for some reason.  I don't know why.

### CODE REVIEW

**Comment by CarbonAlabel** [comment]
The character resource doesn't require any scopes.

**Comment by Blacksmoke16** [comment]
Fixed.

**Comment by polarina** [comment]
Can you rebase your changes on top of current `master` branch? Your pull request is including changes that have already been merged.

**Comment by Blacksmoke16** [comment]
Going to close this, will make a new one when i get my branches fixed

**Pull request closed without merging**
