### PR TITLE
Xmlapi/eve/charactername

### PR DESCRIPTION
**Pull request by HelOWeen**
Typo/word omission fixed: "Please that" -> "Please _note_ that"

### CODE REVIEW

**Comment by Regner** [comment]
Seems to have some artifacts left from a conflict in some of the files.

**Comment by polarina** [comment]
@Regner that's the perfect opportunity to be the nice guy and rebase for them. :-)

I'll do that in a moment.

**Comment by polarina** [comment]
Thanks! Cherry-picked as 81f2f0013eae7f1a964c43d0da6273025e519058.

**Comment by HelOWeen** [comment]
Yeah, I noticed that mess only after I issed the pull request. Sorry for that ... :-(

**Pull request closed without merging**
