### PR TITLE
Add hex column to scope/api mask mapping table

### PR DESCRIPTION
**Pull request by timpanogos**
While I was at it for my imp

### CODE REVIEW

**Comment by polarina** [comment]
What are your opinions on applying the OR operation on the hexadecimal values? That is, for example, `0x00020000 | 0x00040000 | 0x40000000` becomes `0x40060000` in the documentation.

**Comment by CarbonAlabel** [comment]
I'm not a huge fan of this PR. Masks are shown in decimal everywhere else, most importantly the API Key Management page, and support for decimal numbers and `|` as the bitwise OR operator is almost universal in programming languages (but so is the `0x` notation for hexadecimal.)

Any thoughts on that?

**Comment by timpanogos** [comment]
@CarbonAlabel  I assume Programmers doing bit wise programing don't want to think/see decimal.  CPP's presentation of this value to users is just showing them a magic number.  They don't care.  

After realizing they have condensed multiple api bits into single crest scopes, I'd actually prefer something totally different.  @polarina has the most interesting long value to a programmer i.e. just show the final value and have the table look like this:

Scope                                    Api names                                mask
characterWalletRead   transactions, journal, balance      0x00600001 (6291457)

Now its clear exactly what is going on

**Comment by timpanogos** [comment]
Also note there is at least one scope missing: characterLocationRead

I would be glad to give the https://community.eveonline.com/support/api-key/CreatePredefined?accessMask=0 a good once over compared to the current scopes and do a new table per my above suggestion if everyone agrees  with that proposal

**Comment by CarbonAlabel** [comment]
That depends on the programmer. Maybe someone prefers them to be in binary, maybe someone else prefers them in octal, maybe someone would like them to be in ternary or base 64. In the end, it is all the exact same number. By listing the same number in different bases the only thing you get is an enormous table which doesn't provide you with any more information than the one with only two columns, and I feel that the best choice here is using decimal.

When I put the tables in the documentation, I just copied over the list of mappings as it was listed in the [patch notes](https://community.eveonline.com/news/patch-notes/patch-notes-for-eve-online-citadel). I wouldn't have a problem with the final value being listed alongside the individual masks.

Also, these aren't CREST scopes. They are SSO scopes, which may be used to access private parts of both CREST and the XML API. _Side note: the Create new application form on the developers site should be updated to reflect this._

For example, the `characterContactsRead` scope is utilized by both CREST and the XML API, the `characterAssetsRead` scope can only be utilized by the XML API, and the `characterLocationRead` scope can only be utilized by CREST. So no, there aren't any scopes missing in this list.

**Comment by cvweiss** [comment]
CCP's API management page uses base 10, documentation should match.

**Comment by timpanogos** [comment]
So, do I as originator hit close and comment to simply kill/forget this pull request?

**Comment by timpanogos** [comment]
I agree with everyone that the existing PR should be canned.  However I do believe, maybe some other time, that the following suggestion is better than what is there; 

Scope Api-names mask
characterWalletRead transactions, journal, balance 0x00600001 (6291457)
is better than what is there.

@CarbonAlabel I quoted some of your last statement here:
https://forums.eveonline.com/default.aspx?g=posts&m=6561765#post6561765

If SSO access token obsoleted KeyId/Code for xml/api endpoints, the table should simply be deleted.

**Comment by CarbonAlabel** [comment]
SSO access tokens haven't obsoleted API keys. As it says on the page, there is some information which can only be accessed using API keys, and that information is considered very important by some people, which is why I assume API keys still account for a vast majority of XML API's use.

**Comment by timpanogos** [comment]
I've been using the java eveapi until impl my own sax xml parsing for the xml/api.  It was not until to day that I looked closer at implementing my own async xml/api client like I have for the crest.

Note the following documentation:

https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html#authentication 
https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html#usage  

It seems to indicate that If I am setup with SSO, then the API keys are obsolete, perhaps legacy/deprecated etc. would be a better term?  I understand that the xml api interfaces are not going away anytime soon, I just did not expect "two ways" being supported.

Once again, if the KeyId/code is currently legacy with SSO providing equal functionality via the xml/api endpoints ... the table is trivia and should be deleted.

**Comment by CarbonAlabel** [comment]
If you read [this](https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html#sso-access-tokens) paragraph, it says that they are limited in that they cannot be used for account level access, which is why they aren't obsolete, deprecated or legacy in any way.

**Comment by timpanogos** [comment]
To this point in the documentation, I don't believe I've seen the term "account level access".  Yes I saw that statement but I don't understand what it means.  I've seen references to Character and Corporation but not account level??

**Comment by polarina** [comment]
@timpanogos correct. You can create account-level API keys. There is no equivalent for account-level access via the SSO.

**Comment by timpanogos** [comment]
I guess we are talking about these four)?

public interface AccountInterfaces
{
	public AccountStatus getAccountStatus(CrestClientInfo clientInfo) throws SourceFailureException;
	public ApiKeyInfo getApiKeyInfo(CrestClientInfo clientInfo) throws SourceFailureException;
	public Characters getCharacters(CrestClientInfo clientInfo) throws SourceFailureException;
	public CallList getCallList(CrestClientInfo clientInfo) throws SourceFailureException;
}

**Comment by timpanogos** [comment]
from the key maint page, it appears maybe only AccountStatus is keyed

**Comment by polarina** [comment]
@timpanogos these four endpoints will work with an SSO access token. CallList is unauthenticated even.

**Pull request closed without merging**
