### PR TITLE
Proposed Technical Specification structure (auto-generated)

### PR DESCRIPTION
**Pull request by timpanogos**
Please keep the end goal outlined in the following PR in mind as you
consider accepting the PR

[previous pr](https://github.com/ccpgames/eveonline-third-party-documentation/pull/212#issuecomment-244253260)

A new documentation pattern has been suggested which implies all
endpoints would adopt the pattern.  See TournamentCollection for temporary comments about the pattern. (comments moved to [top of this file](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/terminology.txt), )

I have not completed the new ###Data section (finished) on the EndpointCollection or Options
endpoints.  I will complete these upon approval of the proposed pattern. (done)
I also suck at md and not sure of a nice layout to represent an objects
typing yet. (went with pseudo structure)

The TournamentCollection (short the temporary comments) is an example of
a place holder for endpoints discovered via the schema but not yet
documented.   Bottom line here, capture all we know, with liberal use of (TBD) allowing other authors to quickly fill in the blanks with little work on there part.

### CODE REVIEW

**Comment by ChrisHampu** [comment]
If you are planning on suggesting a new documentation pattern that still leverages the ease-of-use of Markdown syntax, I'd be inclined to recommend using the syntax of [https://apiblueprint.org](https://apiblueprint.org).

It's easy to format, easy to read, and is a common format that can be verified for errors and correctness. As such, strict formatting can be applied globally to all documentation. Another advantage is that it has a lot of great tooling, and can even be directly rendered into complete self-contained HTML that can be served as a documentation webpage. It can also be converted into other documentation formats such as Swagger if a change in direction is desired in the future.

That is my simple proposal for a documentation syntax and style.

**Comment by timpanogos** [comment]
@jonobrien @CarbonAlabel
Release candidate up,  I'm moving back to coding.  

See this thread for detailed discussion: https://github.com/ccpgames/eveonline-third-party-documentation/pull/212#issuecomment-244253260

**Comment by timpanogos** [comment]
CCP employees, see [probable schema bugs](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/schemaIssues.txt) in this temporary file.

**Comment by CarbonAlabel** [comment]
Let me address your list of issues:

1. It's not an endpoint collection, it's the root resource, and aside from links to certain endpoints, it also reports on the status of the servers (`serviceStatus`) and current player count (`userCount`), which is why it needs such a short cache time (We could argue it should be even lower.)
2. Why are you expecting it to be present? It is listed as optional, and is only present for endpoints and methods which accept a representation instead of returning one.
3. I can assume the route was added early in development, a representation wasn't added because of CCPs privacy policies, and the route remains in place for whatever reason.
4. How is this an issue? The same happens on several other endpoints, and the order in which the representations are returned isn't guaranteed anywhere.
5. The endpoint in question is used by the EVE Online client. CREST isn't just a third-party API, it's also used internally by CCP, and was in fact initially built as an internal API.
6. An endpoint may handle multiple types of representations, not just different versions. I think introducing such a field would only lead to further problems, and clients shouldn't be expected to perform pattern matching.
7. It is listed under `itemTypes`.
8. I would be OK with this changing next time backwards compatibility breaking changes are made to the root endpoint.
9. Why should they? What advantages would this offer? The endpoints you listed can't really be considered members of a category. Pigeonholing them into one just for the sake of it wouldn't help.
10. _"A program should
be able determine all the endpoints/schema without being authenticated."_ Arguable. Getting an access token isn't that hard, and will be required anyway to test the app once it's complete.
11. Yes, the documentation is incomplete.
12. Because of JavaScript.
13. I'll put in a pull request detailing this behaviour.
14. I disagree. Wrapping the links in objects opens up an interesting possibility: by replacing an object containing a `href` property with the object returned by performing a GET request on the URL (with some extra considerations for paginated collections) it is possible to view CREST as a self-referencing super-object, resulting in a very elegant (also somewhat difficult to implement) way of accessing the API which abstracts away the very concept of APIs and endpoints.

**Comment by jonobrien** [comment]
for your bug point 12, there's devblogs/forum posts about reasoning behind any of the *_str inclusion in the json response.

**Comment by timpanogos** [comment]
hmm, I really only intended that temp list for ccp IF they were interested in an enhancement request bug I had already written on the schema.  It is just a more complete list of things I came across while digging through the schema.  I'd really rather just leave this up to them to decide if there is any value in my experience with an oop and working with the existing schema.

@CarbonAlabel One note however on your comments to item 1.  The proposed new name/term for "root resource" is EndpointCollection.  I could not find a schema definition for this object (Access string in particular) but have proposed it now be called EndpointCollection as that matches all other schema'ed objects that have an item list.  As for service status checking I personally used the Time endpoint for a repeating heartbeat as it had the fastest refresh time of any endpoint.  I use the xmlApi's apiCallList to check that root for the same reason.

Please constrain comments to the [index.md](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/index.md), [endpointCollection.md](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/endpointCollection.md), [options.md](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/options.md), [tournament .md](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/tournamentCollection.md) and suggested [terminology/pattern rules](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/terminology.txt) being submitted for immediate merge to master as ccp deems fit.

I'm working on parsing the Tournament json now in my framework and will likely do a more accurate description in the Tournament.md, now I see how it works.  Perhaps I'll take a stab at a generic page walking description, but I'm avoiding too much more trickle until we get some feedback from ccp. on these proposals.

**Comment by OrthoLoess** [comment]
>Please constrain comments to the index.md, endpointCollection.md, options.md, tournament .md and suggested terminology/pattern rules being submitted for immediate merge to master as ccp deems fit.

If this was what you wanted, you should not have made a PR with other files in it.

Are you hoping for any/all of this PR to be merged, or is this just for discussion again?

Certainly, your list of perceived issues and the accompanying options dump has no place in the docs, so should not really be included in a PR.

**Comment by timpanogos** [comment]
@OrthoLoess 
If you are a ccp employee and have considered the information in the *.txt files while considering the radical changes to the existing documentation that I'm proposing (with TournamentCollection.md being the suggested pattern), then I'll delete those files in hopes of pressing forward with this PR

**Comment by OrthoLoess** [comment]
I am not a CCP employee, just trying to help you understand how best to contribute to the docs project.

**Comment by timpanogos** [comment]
@OrthoLoess sorry I edited my previous post, please re-read.  I thank you for your input.  I do believe this is a special case that required the extra information because of how radically this proposed changed is, and following PR's that I would make restructuring the doc.

**Comment by timpanogos** [comment]
btw, ccp-bartender sent me some valid endpoints (my last night) for the multiple Tournament*.md files I added last night.  The reported first tournament ID's uri 404'ed but I figured there would be nine of them, he sent me five good ones.

I'll press forward with trying to fill out the five of the nine I added.

**Comment by OrthoLoess** [comment]
I'm not really sure what you're trying to achieve, what you think is wrong at the moment, etc.

You spoke about making it all machine readable, which is entirely against the core purpose of these docs, as carbon said earlier, there are other projects out there doing that. This repo is for a set of docs that real humans come to to find answers to help them code for the APIs

With that in mind: renaming the root to EndpointCollection seems pointless and counter-productive. That describes part of what it does, but does not help understand what it _is_.

The options page is a good idea at base, but it fails to explain what options calls are or how to use them and gets very confused about whether it is talking about options calls to the root or to other endpoints.

Looking at the suggested tournament endpoint page on its own, it looks pretty good (although the markdown formatting for the header quote could be better)

**Comment by OrthoLoess** [comment]
One more thing: while it may well be useful to have the route for each endpoint included on its page, using it in code is breaking the guidelines on how to use crest. It would be even more useful to have the steps required to walk to the endpoint.

**Comment by timpanogos** [comment]
@OrthoLoess 

> One more thing: while it may well be useful to have the route for each endpoint included on its page, using it in code is breaking the guidelines on how to use crest. 

If the EndpointCollection.md and Options.md  are accepted I would immediately drop a new PR for a generic page on generating dynamic urls and checking versions by utilizing these endpoints.  Of course no one should hardcode their uri's based on the documentation.

> It would be even more useful to have the steps required to walk to the endpoint.

This also sounds like a generic page that would describe the ###Parent, ###Children and ###Descendants elements of the proposed template.  Of course we need to agree on the template first.

**Comment by timpanogos** [comment]
@OrthoLoess 

> I'm not really sure what you're trying to achieve, what you think is wrong at the moment, etc.

1. Document how to dynamically obtain endpoint urls and how to check your implemented version against what is being delivered at the current time.
2. Drive all naming off of the schema's "Access Base"
3. Organize endpoint.md's by EndpointCollection's Group's, making a name up where it is not given (currently only a misc or other group would be needed, all existing would then fall into reasonable groups).
3a. never put multiple endpoints in a single .md
4. Replace the current ###Get sections (variable name, snapshot value) with a ###Data section (type, variable name, optional, description from schema)

> You spoke about making it all machine readable, which is entirely against the core purpose of these docs, as carbon said earlier, there are other projects out there doing that. This repo is for a set of docs that real humans come to to find answers to help them code for the APIs

Any talk I gave about machine readable was intended as a one-shot deal where I would use my code to auto-gen all of the ###Data sections from the existing schema.  It turns out this is all down the drain as the schema does not match the endpoints returned object (i.e. no _str's).  This this will have to be a manual process for each one (or we get accurate schema).

> With that in mind: renaming the root to EndpointCollection seems pointless and counter-productive. That describes part of what it does, but does not help understand what it is.

I would immediately PR a generic .md to explain the use of EndpointCollection Options and how they play into the overall structure of the documentation.

> The options page is a good idea at base, but it fails to explain what options calls are or how to use them and gets very confused about whether it is talking about options calls to the root or to other endpoints.
same as above.  Hopefully the existing Options.md is clear on using the root or endpoint, otherwise I need to clarify more.

> Looking at the suggested tournament endpoint page on its own, it looks pretty good (although the markdown formatting for the header quote could be better)

wide open for template suggestions.

**Comment by OrthoLoess** [comment]
Ok, it's making more sense to me now. some thoughts, not in any particular order:

>This also sounds like a generic page that would describe the ###Parent, ###Children and ###Descendants elements of the proposed template. Of course we need to agree on the template first.
There is already a generic page on walking (could use improvement, I'm sure), however for some, if not many, endpoints, how you walk to them is not obvious from the url. I don't see the need to make people go up through the parents to get this, so why not put it on the page for the resource? e.g.
>root -> decode -> character -> contacts

You currently have the Options page listed as an endpoint, which it is not. It's a call that can be performed on any endpoint, so I'd put it somewhere other than under the eve endpoint group

The root is not just an endpoint, it is very much a special case and should be treated that way, it will be the first thing you need to use, put it somewhere obvious (with a name that doesn't obfuscate it).

The idea of having a well defined and non-ambiguous representation of the expected data type is good, however I see no reason not to also keep the example (currently under the GET heading in many). Examples are useful for understanding.

On the subject of whether a GET and POST to the same endpoint URL should be in separate pages, I am undecided. I'm leaning towards not, as I think this would be clearer.

If there is something special to say about the options return for a particular endpoint, just add a section to that endpoint's page for it.

Make sure you are fully aware yourself and clear in the guidelines for endpoint formatting etc that this is all only about the endpoints section of the CREST section of the docs. There are all sorts of other things that it does not apply to.

**Comment by timpanogos** [comment]
@OrthoLoess **_finally_** a constructive review thank you very much.

one question ... what is an Endpoint to you guys?  In my quick and dirty terminology.txt file I tried to suggest that it is any url that returns a unique json object graph.  i.e. it's another term for a function or method that returns a value.  For example in pseudo code I just finished these two endpoints/functions

* `public Tournament getTournament(long tournamentId)`
* `public Series getTournamentSeries(long tournamentId)`

Thus rather an http.options call on a url or a http.get call on root or not, to me I'm just viewing these as a unique function (and perhaps wrongly calling it an endpoint).  Bottom line, organization can be determined, my push at this point is a unique .md per "function" ... I'm ok with same for get/post as you suggested ... I have not gotten into any setters yet.

I believe most all of your comments are valid and we should bring them up IF cpp has any interest in where this is going ... I just keep pouring work into this doc which might not be of any interest to them.

I'll try pinging ccp-bartender to see if we can get a simple; "yes we are interested continue with the Tournament tree", or we are not interested in this approach don't waste any more time on it.

**Comment by timpanogos** [comment]
@OrthoLoess 
I ended up taking a stab at some of your suggestions:
> root -> decode -> character -> contacts

see if the very end of the description now covers what you are suggesting here. https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/misc/tournament/tournamentCollection.md

> You currently have the Options page listed as an endpoint, which it is not. It's a call that can be performed on any endpoint, so I'd put it somewhere other than under the eve endpoint group

moved endpointCollection.md, Options.md and temp schema related .txt files under `.../misc/schema`

> (with a name that doesn't obfuscate it)

Please suggest names, I only went with that one because all other endpoints that return a list end in the name Collection.  This is the one special endpoint (or function or whatever) that does not have it's name specified in schema.  Feel free to name it, I'm not hung up on this name.

> however I see no reason not to also keep the example (currently under the GET heading in many). Examples are useful for understanding.

Added ### Samples right after ###Data, see the following:

https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/misc/tournament/tournamentCollection.md

https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/misc/tournament/tournamentGetTournament.md

https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/misc/tournament/tournamentGetSeries.md

> On the subject of whether a GET and POST to the same endpoint URL should be in separate pages, I am undecided. I'm leaning towards not, as I think this would be clearer.

I have not even thought of this yet.

> If there is something special to say about the options return for a particular endpoint, just add a section to that endpoint's page for it.

I personally view each option as a unique endpoint, the certainly contain all the same template elements with the type of http client call being the only difference.  We could add ### Options links like I did the parent/children convenience links, or I could be convinced add another Option Data and Option Sample section to each.  I'd like to hear other thoughts on this.

> Make sure you are fully aware yourself and clear in the guidelines for endpoint formatting etc that this is all only about the endpoints section of the CREST section of the docs. There are all sorts of other things that it does not apply to.

I'm not clear on what you are telling me here

**Comment by OrthoLoess** [comment]
I'll have a proper look later, but a couple of immediate points:

>see if the very end of the description now covers what you are suggesting here.
Not even slightly 😛 
I literally mean the set of jumps you need to take when walking to it from the root (might be multiple options). The example I used was chosen to reflect the problem: the decode step does not appear in the URL for the endpoint, but you do have to walk via it. This information is not immediately obvious...

>Please suggest names
RootEndpoint
I know it doesn't really fit with the others, but nor does the endpoint. I'd also put it a level up, directly under the Calls heading.

>I personally view each option as a unique endpoint, the certainly contain all the same template elements with the type of http client call being the only difference.
I certainly don't think we need a separate page for every options call, as most of the information is the same, or contained in the ###Data section (ish). I'd just take the Options page out of the 'Calls' section and keep it as a general explanation of how to use options, with some specifics, like for the root endpoint.

>I'm not clear on what you are telling me here
See the options.md: most references to EVE should read CREST. (very short version of explanation)

**Comment by timpanogos** [comment]
god I suck at tech-writing, I think I see what you mean on the eve/crest.

I still think I know what you mean on the jumps ... this particular set of endpoints is particularly nasty as some are declared via uri segments while other aspects need to be rooted out of the returned data of a previous endpoint.   Note all the (TBD)'s still in the docs as I was focused only on getting these things parsed to get the raw data.  My special snowflake is a java api framework (i.e. not an application) into xmiapi and crest.  After I get all the tournament data marshalled into my world ... then I can write a walking application on top of my api's and finalize the finer point descriptions on all those TBD's

**Comment by jonobrien** [comment]
you should really break out your docs into another PR if you want those added as well, I've been working on many nuances about the `/tournaments/` endpoints myself as well.

**Comment by timpanogos** [comment]
Since the EndpointCollection (RootEndpoint) and options are so out of date and broken in the first place, driving the documentation's standards based on auto-discovery of uri's and version checking might not be the best idea.  Early on I had hoped I could auto-generate the bulk of the work, which is not going to be possible with todays schema/RootEndpoint.

perhaps all I have done is upset the regular's who have a lot more time vested in this than I.

With @CarbonAlabel proposing his own standard, I'll bow out and leave you all to some peace.

see
https://github.com/ccpgames/eveonline-third-party-documentation/pull/220

**Comment by jonobrien** [comment]
you've made some good points, depends on what others think. Certainly is a lot to change with 1 PR it seems, but that might just be because some of it is outdated, as you've said, or some items have not been even mentioned before, or addressed accordingly.

**Comment by jonobrien** [comment]
you might want to rename the file to match the naming_conventions other already did, the camelCasing seems out of place in that location.

**Comment by timpanogos** [comment]
@jonobrien I pulled all of my naming from the schema which uses camel case, it was one of my suggested rules.  The assumption is that developers are actually using the RootEndpoint/Options to dynamically build their url's and hence the naming in the documentation would align with the "Access base, leaf name" which appears to intentionally be a Unique Identifier for the desired returned json object graph.

For example: 
"application/vnd.ccp.eve.AllianceCollection-v2+json" is the UID of the the json object graph that is expected to be returned.  For those anal like me, my coding names will follow this "specification" i.e. AllianceCollection.java and it's typically good for documentation on that data to follow the providers "assigned" name.

As far as the PR getting large ... it's all new endpoints thus no collisions.  Going to a more lenient criteria with liberal (TBD's) getting the bulk of known information in where it's totally missing should be good.

I'm working on a full set of api's and thus could provide say all the Data and Sample sections, while application people might learn individual endpoint navigation tricks (tournaments has a shit ton of external url's in the data, some of which I quickly noted return json for example) and add this at a future date.

good news is ccp is watching and interested.

**Comment by jonobrien** [comment]
@timpanogos  yes I saw that, I am about to PR my huge tournaments edit, you could edit that after I push up all the editions if you and @CarbonAlabel or anyone else has decided on a new theme for documenting things.

**Comment by jonobrien** [comment]
I don't think you want to constrain users to thinking they have to use a single language to query the api, imho you should probably try to leave language syntax out of your documentation.

**Comment by jonobrien** [comment]
I don't think you want to constrain users to thinking they have to use a single language to query the api, imho you should probably try to leave language syntax out of your documentation.

**Comment by jonobrien** [comment]
@timpanogos, there is a duplicate json uid string for tournament teams, I documented in #221 that has different data but same content-type

**Comment by timpanogos** [comment]
> there is a duplicate json uid string for tournament teams, I documented in #221 that has different data but same content-type
note to self for ccp wish list: Tournament.TournamentTeam-v1+json is duplicated see TeamStatus

**Comment by timpanogos** [comment]
>  I am about to PR my huge tournaments edit, you could edit that after I push up all the editions if you and @CarbonAlabel or anyone else has decided on a new theme for documenting things.

I think this is fine.  We don't want to leave a mess around for a long time, but some "agile" work of merging all three of these changes to master and narrowing this down with a final clean up works for me.

Version control's are nice for capturing stuff one might want to go back to.  I wonder if we can branch the master instead of forking it? if we could share each others branches that would help as well.

What I do suggest if we can go to this agile, under construction concept for this major of proposed changes, is we all move our stuff under some "underConstruction" root folder or some such so as not to disrupt normal usage.

**Comment by timpanogos** [comment]
> I don't think you want to constrain users to thinking they have to use a single language to query the api, imho you should probably try to leave language syntax out of your documentation.

I understand this and agree with it ... IF any code examples are deemed useful it would defiantly want to be pseudo code not representing any given language (except for JS which is special around these parts :) )

**Comment by timpanogos** [comment]
@jonobrien 
actually your .md  follows existing doc, so your's might as well go in normally so others can use it now

**Comment by jonobrien** [comment]
@timpanogos you could checkout our branches and merge them yourself and then PR that new merged branch back into CCPs main here

**Comment by jonobrien** [comment]
@timpanogos CCPSoon(tm)

**Comment by timpanogos** [comment]
@jonobrien a little birdie told me things look bright ... I think good news follows soonish.

**Comment by jonobrien** [comment]
that's a lotta css :+1:

**Comment by timpanogos** [comment]
well, its bare but that shows about as wide as it would get at the root even with all xmlapi eventually coming over.   The other thing to do I suppose is to try grouping the whole thing by functionality, problem is it ends up pretty wide anyway with the number of existing double segmented [group][endpoints].

**Comment by polarina** [comment]
Can this pull-request be rebased on top of current master, please?

**Comment by timpanogos** [comment]
I wonder why the sudden activity?  I was expecting new information after csm summit this week?

**Comment by timpanogos** [comment]
@polarina 

> Can this pull-request be rebased on top of current master, please?

done

**Comment by timpanogos** [comment]
@polarina 
I'm done playing with this for now, there are still a few broken links but the overall concept this shown:
Start at the following index, take the "under construction" link and navigate from there.

https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/index.md

There is a .md page per unique accept uid (including post, get, put and delete).  The uid, url, relative uri and several cache timers have been captured.  The .md file names are obtained from the uid.  The paths leading to the .md files matches the url.   Cache timers for all endpoints that do not contain an ID or require authentication have been captured.

I've also got the RootEndpoints, Options and some of the Tournament endpoints documented somewhere in all that mess, which would be merged into the auto-gen.  My biggest interest right now is in capturing all we know and setting up an extensible documentation structure.

**Comment by jonobrien** [comment]
This is getting huge, you might want to rename this to clarify intentions of the PR.

**Comment by tsuthers-ccpgames** [comment]
Hey all, boy this one got big!

Unfortunately, it's too big for us to do a meaningful review on, I can't go through 90 markdown files in a single merge with any degree of confidence.

My main concern with this kind of massive refactor is that it might break links to the documentation in old forum posts etc, but it's really impossible for me to evaluate that on a PR of this size.

I'm going to close this PR even though I can see a great deal of work and enthusiasm has gone into it. It needs to be broken up into smaller chunks of logically grouped changes that can be integrated independent of each other, so that the changes can be reviewed in a sane way. During that process, it's important to consider leaving a trail of stub pages for probable broken links (if that wasn't done here already).

**Pull request closed without merging**
