### PR TITLE
Explanation of _str properties in CREST

### PR DESCRIPTION
**Pull request by CarbonAlabel**
In response to question asked in #215

### CODE REVIEW

**Comment by timpanogos** [comment]
really 2 ^53, start losing precision on Long types?  I advanced google searched the dev blogs for _str to see what all the fuss was about.  Adding them originally made no sense to me from the first introduction of them.   Have you notice that only a faction of the longs are duplicated for this supposed problem.  What the heck is js doing with all those other longs?  I have a hard time believing a popular language like js has issues with this.

I don't care about adding this note, other than I hope to god ccp stops doing this for future, new interfaces, along with the fact they seem to have only done it on page counts and total items.  i.e. the usage is inconsitent

**Comment by timpanogos** [comment]
also note, none of the _str's are declared in the schema ([see the options.txt](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/options.txt)) and hence break every schema vs actual value objects return contract.

**Comment by CarbonAlabel** [comment]
@timpanogos Mind pointing out where the usage is inconsistent? I'm pretty sure the `_str` properties are automatically added.

Also, it might be a bit too late to be surprised at some of JavaScript's choices.

**Comment by OrthoLoess** [comment]
It is one of the fundamental points about using crest that you should be able to handle unexpected extras. If you don't need the _strs just ignore them. (the requirement to silently ignore extra returns is related to versioning and backwards compatibility).

Your only objections here seem to be about there being _str's in CREST at all, this is the wrong forum for that. This github is for the documentation and any PRs and issues should be about that, not problems with CREST itself. We seek to document the APIs as-is, rather than impose our opinions of how they should be.

This explanation looks well-written and appropriate to me.

**Comment by timpanogos** [comment]
> Mind pointing out where the usage is inconsistent? I'm pretty sure the _str properties are automatically added.

[note the Data section](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/eve/tournamentCollection.md)
1. The endpoint data is inconsistent with the schema - the schema contract is broken.



Also, it might be a bit too late to be surprised at some of JavaScript's choices.

**Comment by timpanogos** [comment]
@OrthoLoess 

> It is one of the fundamental points about using crest that you should be able to handle unexpected extras. If you don't need the _strs just ignore them. (the requirement to silently ignore extra returns is related to versioning and backwards compatibility).

The ordering of json needs to remain constant, extras (additions) at the end of a previous release is fine, adding extra's at the start and in the middle is not.

my push with the documentation is that it should be driven by the schema, not the values returned.  None of the _str's are declared in the schema and are NOT found appended to the end of the values being returned, but at the beginning and mixed in the middle.

**Comment by OrthoLoess** [comment]
Ordering of a JSON array is important. By the spec, ordering of a JSON object is arbitrary. Your implementation should never assume anything about the order of the key:value pairs. There was a good video from evesterdam a few years ago, going over best practices for using CREST, the topic of needing to silently ignore unexpected keys was covered there iirc.

This documentation is designed to help people use the APIs. It should reflect reality, not what you wish was reality. Since the _str elements are there, the documentation should explain them.

**Comment by CarbonAlabel** [comment]
JSON objects are by definition **unordered** sets of key/value pairs. Besides, we were told by devs several times not to count on ordering of elements returned by API responses in any way.

I also just noticed the message about conflicts. Can someone more experienced with git tell me whether it can be fixed easily or should I redo the PR?

**Comment by OrthoLoess** [comment]
I think it should be pretty easy to resolve on merge, so I wouldn't worry about it unless/until someone asks you to fix it.

**Comment by timpanogos** [comment]
> I also just noticed the message about conflicts. Can someone more experienced with git tell me whether it can be fixed easily or should I redo the PR?

Do a new merge from master to your branch and it will either auto-merge the conflict (different lines) or cause you to need to resolve the same line conflicts.

**Comment by timpanogos** [comment]
> JSON objects are by definition unordered sets of key/value pairs. Besides, we were told by devs several times not to count on ordering of elements returned by API responses in any way.

I thought that if schema was provided order was maintained.  In googling I see I was wrong on this.  None-the-less the current schema does not show the _str's

**Pull request closed without merging**
